{
  "formatVersion": "1.1",
  "component": {
    "group": "su.spyme",
    "module": "marketplace-base",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-status-pages",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-call-logging",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-call-id",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-default-headers",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-config-yaml",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-auth",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-auth-jwt",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-rate-limit",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-core",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-jdbc",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-java-time",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-json",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "10.18.0"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "10.18.0"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "marketplace-base-0.2.0.jar",
          "url": "marketplace-base-0.2.0.jar",
          "size": 1288866,
          "sha512": "20ddc1c3622e00ba454e487b06df525f4dd759d760ea1b1dea1abcfcf794c36dca6b83ac4a21e44384a0feea4a24823f5ba4700f0b372894b2e91318af35fd9f",
          "sha256": "5e8cbfa7e171979b29825401738cd5f5b84fa2550191269e3592b841865eb271",
          "sha1": "bf0a511a0e11cd6cf27787f533f290221a03b88c",
          "md5": "fbeb458ccfffa40d58d9726360df5b22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.yubico",
          "module": "webauthn-server-core",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.84"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.84"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.1.8"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-circuitbreaker",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-kotlin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "it.sauronsoftware.cron4j",
          "module": "cron4j",
          "version": {
            "requires": "2.2.5"
          }
        },
        {
          "group": "net.openhft",
          "module": "zero-allocation-hashing",
          "version": {
            "requires": "0.16"
          }
        },
        {
          "group": "com.github.slugify",
          "module": "slugify",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "com.meilisearch.sdk",
          "module": "meilisearch-java",
          "version": {
            "requires": "0.14.2"
          }
        },
        {
          "group": "io.pebbletemplates",
          "module": "pebble",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.vladsch.flexmark",
          "module": "flexmark-all",
          "version": {
            "requires": "0.64.8"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.3"
          }
        },
        {
          "group": "org.imgscalr",
          "module": "imgscalr-lib",
          "version": {
            "requires": "4.2"
          }
        },
        {
          "group": "io.github.smiley4",
          "module": "ktor-swagger-ui",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.github.pengrad",
          "module": "java-telegram-bot-api",
          "version": {
            "requires": "7.9.0"
          }
        },
        {
          "group": "org.eclipse.angus",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "net.logstash.logback",
          "module": "logstash-logback-encoder",
          "version": {
            "requires": "8.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-registry-prometheus",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-status-pages",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-call-logging",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-call-id",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-default-headers",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-config-yaml",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-auth",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-auth-jwt",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-rate-limit",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-core",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-jdbc",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-java-time",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-json",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "10.18.0"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "10.18.0"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "marketplace-base-0.2.0.jar",
          "url": "marketplace-base-0.2.0.jar",
          "size": 1288866,
          "sha512": "20ddc1c3622e00ba454e487b06df525f4dd759d760ea1b1dea1abcfcf794c36dca6b83ac4a21e44384a0feea4a24823f5ba4700f0b372894b2e91318af35fd9f",
          "sha256": "5e8cbfa7e171979b29825401738cd5f5b84fa2550191269e3592b841865eb271",
          "sha1": "bf0a511a0e11cd6cf27787f533f290221a03b88c",
          "md5": "fbeb458ccfffa40d58d9726360df5b22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "marketplace-base-0.2.0-sources.jar",
          "url": "marketplace-base-0.2.0-sources.jar",
          "size": 246625,
          "sha512": "b9865a1210db57e92e649ca0e453e5ed426582a8e9506dffd12c155d0f552ce77fcc105c647a0e0891caddd2f493a7af2ef61fb3abd7c75af3ff641fa9009694",
          "sha256": "6109b0aba0a3c4b3a0d7714b1fbeffb9a5db9f7c74498f8acfe6a26bd8dc41e7",
          "sha1": "00a08b73e0317e797ece2bda6ec65af7f117e066",
          "md5": "73daad883cdbbe2eaa0b89295ab7efc9"
        }
      ]
    }
  ]
}
