{
  "formatVersion": "1.1",
  "component": {
    "group": "su.spyme",
    "module": "marketplace-base",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-core",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-jdbc",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-java-time",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-json",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "10.18.0"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "10.18.0"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "marketplace-base-0.4.0.jar",
          "url": "marketplace-base-0.4.0.jar",
          "size": 1294612,
          "sha512": "935596dd570cca500ea1487105a937f711ad82e35e2c9cce219e813bd4a9e56b3b9d9e5db2f4ba95b79c64b375cd551cb72802d122300408c474dc0efb514cf5",
          "sha256": "9c58e1a71a4f047a0092bfe29df942484976a0f2b867d138329a56a51c875977",
          "sha1": "00a3316c7805759ea9962171ed858509554d4760",
          "md5": "2913d50e77030414363c790890d1c544"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.84"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.1.8"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-circuitbreaker",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-kotlin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.meilisearch.sdk",
          "module": "meilisearch-java",
          "version": {
            "requires": "0.14.2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-core",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-jdbc",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-java-time",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-json",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "10.18.0"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "10.18.0"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "marketplace-base-0.4.0.jar",
          "url": "marketplace-base-0.4.0.jar",
          "size": 1294612,
          "sha512": "935596dd570cca500ea1487105a937f711ad82e35e2c9cce219e813bd4a9e56b3b9d9e5db2f4ba95b79c64b375cd551cb72802d122300408c474dc0efb514cf5",
          "sha256": "9c58e1a71a4f047a0092bfe29df942484976a0f2b867d138329a56a51c875977",
          "sha1": "00a3316c7805759ea9962171ed858509554d4760",
          "md5": "2913d50e77030414363c790890d1c544"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "marketplace-base-0.4.0-sources.jar",
          "url": "marketplace-base-0.4.0-sources.jar",
          "size": 250473,
          "sha512": "3f14f5d576c5b3ae3b123efb66d698e30c2d76814d94a0d1fddddcb244ae662398423d2496dea0ee1574f3f987ff94a4b4191a96e688b0bbf8e92596068725b3",
          "sha256": "2e268ba5777e7aca148520061c61bed0e1b35b8e9437aafd07d69f4050e23da6",
          "sha1": "6efbb08b80a73a8d24cce12a825f14b94beb85c6",
          "md5": "050cfefd00281e19598ef1d5b248b442"
        }
      ]
    }
  ]
}
