{
  "formatVersion": "1.1",
  "component": {
    "group": "su.spyme",
    "module": "marketplace-base",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-status-pages",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-call-logging",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-call-id",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-default-headers",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-config-yaml",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-auth",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-auth-jwt",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-rate-limit",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-core",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-jdbc",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-java-time",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-json",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "10.18.0"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "10.18.0"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "marketplace-base-0.3.0.jar",
          "url": "marketplace-base-0.3.0.jar",
          "size": 1294787,
          "sha512": "6c8d44cf8c87ce8d5fa1501c2d1659475ca2b6d6d1a450fd5caaef7bd62008ce8c540c4cb63ea607c426ff1d64a05c0b9c8c882d526d55ef6865463f5fc94bce",
          "sha256": "3b73e116d4e2bd956c969a1b5cde61c9e598c50bf5a1801d749110b94366626e",
          "sha1": "9f26d28e99e9d63a91ab97d958f169a13e835392",
          "md5": "5def7d6337dd24ded5ff19c284ec36df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.yubico",
          "module": "webauthn-server-core",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.84"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.84"
          }
        },
        {
          "group": "com.github.ben-manes.caffeine",
          "module": "caffeine",
          "version": {
            "requires": "3.1.8"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-circuitbreaker",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-kotlin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "it.sauronsoftware.cron4j",
          "module": "cron4j",
          "version": {
            "requires": "2.2.5"
          }
        },
        {
          "group": "net.openhft",
          "module": "zero-allocation-hashing",
          "version": {
            "requires": "0.16"
          }
        },
        {
          "group": "com.github.slugify",
          "module": "slugify",
          "version": {
            "requires": "3.0.7"
          }
        },
        {
          "group": "com.meilisearch.sdk",
          "module": "meilisearch-java",
          "version": {
            "requires": "0.14.2"
          }
        },
        {
          "group": "io.pebbletemplates",
          "module": "pebble",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.vladsch.flexmark",
          "module": "flexmark-all",
          "version": {
            "requires": "0.64.8"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.18.3"
          }
        },
        {
          "group": "org.imgscalr",
          "module": "imgscalr-lib",
          "version": {
            "requires": "4.2"
          }
        },
        {
          "group": "io.github.smiley4",
          "module": "ktor-swagger-ui",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.github.pengrad",
          "module": "java-telegram-bot-api",
          "version": {
            "requires": "7.9.0"
          }
        },
        {
          "group": "org.eclipse.angus",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "net.logstash.logback",
          "module": "logstash-logback-encoder",
          "version": {
            "requires": "8.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-registry-prometheus",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-status-pages",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-call-logging",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-call-id",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-default-headers",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-config-yaml",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-auth",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-auth-jwt",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-rate-limit",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-core",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-jdbc",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-java-time",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "org.jetbrains.exposed",
          "module": "exposed-json",
          "version": {
            "requires": "0.57.0"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "6.2.1"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.7"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "10.18.0"
          }
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-database-postgresql",
          "version": {
            "requires": "10.18.0"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "marketplace-base-0.3.0.jar",
          "url": "marketplace-base-0.3.0.jar",
          "size": 1294787,
          "sha512": "6c8d44cf8c87ce8d5fa1501c2d1659475ca2b6d6d1a450fd5caaef7bd62008ce8c540c4cb63ea607c426ff1d64a05c0b9c8c882d526d55ef6865463f5fc94bce",
          "sha256": "3b73e116d4e2bd956c969a1b5cde61c9e598c50bf5a1801d749110b94366626e",
          "sha1": "9f26d28e99e9d63a91ab97d958f169a13e835392",
          "md5": "5def7d6337dd24ded5ff19c284ec36df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "marketplace-base-0.3.0-sources.jar",
          "url": "marketplace-base-0.3.0-sources.jar",
          "size": 249733,
          "sha512": "89c63b443bbb0681590d659bead9441518a6ea7611bd555815a5ac03d8d392a6ff44b0dd64d5ed7881ae73aa180df2437a290ebcb06140f051ce8c28142450dd",
          "sha256": "39a2905a484219309d000c1b6f9b117736891c34978a1c46c3a20886b99ffc8b",
          "sha1": "4b8edbf72e820c8fa49223a5b30e6c0cf7feacfe",
          "md5": "4a9fc36289d2344de164af08137a9681"
        }
      ]
    }
  ]
}
